name: Atualizar Cardápio Diário

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
          fetch-depth: 0 # Baixa todo o histórico para permitir o rebase corretamente

      - name: Configurar Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Sincronizar com GitHub (Evitar Conflitos)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          # Puxa as alterações mais recentes do GitHub antes de rodar o robô
          git pull --rebase origin main

      - name: Rodar robô de atualização
        run: python atualizar_cardapio.py

      - name: Salvar alterações no Git
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "🤖 Atualização automática do cardápio"
          file_pattern: menu.json index.html assets/fotos
          branch: main
